// packages/auth/src/react/AuthProvider.tsx
import { createElement, useEffect, useMemo, useSyncExternalStore } from 'react'
import type { ReactElement, ReactNode } from 'react'
import type { AuthClient } from '../client/auth-client'
import { createAuthSession } from '../bindings/create-auth-session'
import { AuthContext } from './auth-context'

interface AuthProviderProps {
	client: AuthClient
	children: ReactNode
	fallback?: ReactNode
}

function AuthProvider({ client, children, fallback }: AuthProviderProps): ReactElement {
	const session = useMemo(() => createAuthSession(client), [client])

	useEffect(() => () => session.destroy(), [session])

	const snapshot = useSyncExternalStore(
		(onStoreChange) => session.subscribe(onStoreChange),
		() => session.getSnapshot(),
		() => session.getSnapshot(),
	)

	if (snapshot.initError) {
		return createElement(
			'div',
			{
				style: { color: 'red', padding: '1rem', fontFamily: 'monospace' },
				role: 'alert',
			},
			createElement('strong', null, 'Kora Auth initialization error: '),
			snapshot.initError.message,
		)
	}

	if (snapshot.isLoading && fallback !== undefined) {
		return fallback as ReactElement
	}

	const contextValue = {
		client,
		session,
		state: snapshot.state,
		isLoading: snapshot.isLoading,
	}

	return createElement(AuthContext.Provider, { value: contextValue }, children)
}

export { AuthProvider }
export type { AuthProviderProps }

// packages/auth/src/svelte/AuthProvider.svelte
<script lang="ts">
import { onDestroy } from 'svelte'
import type { AuthSessionSnapshot } from '../bindings/create-auth-session'
import type { AuthClient } from '../client/auth-client'
import { destroyAuthProvider, initAuthProvider } from './auth-context'

interface Props {
	client: AuthClient
	fallback?: import('svelte').Snippet
	children?: import('svelte').Snippet
}

const { client, fallback, children }: Props = $props()

const authContext = initAuthProvider(client)
let snapshot = $state<AuthSessionSnapshot>(authContext.session.getSnapshot())

$effect(() => {
	return authContext.session.subscribe(() => {
		snapshot = authContext.session.getSnapshot()
	})
})

onDestroy(() => {
	destroyAuthProvider(authContext)
})
</script>

{#if snapshot.initError}
	<div role="alert" style="color: red; padding: 1rem; font-family: monospace;">
		<strong>Kora Auth initialization error: </strong>{snapshot.initError.message}
	</div>
{:else if snapshot.isLoading && fallback}
	{@render fallback()}
{:else if children}
	{@render children()}
{/if}
