// packages/cli/templates/vue-tailwind/src/App.vue
<script setup lang="ts">
import { CheckCircle2, Circle, ClipboardList, Loader2, Plus, Trash2 } from 'lucide-vue-next'
import { computed, ref } from 'vue'
import { useTodos } from './modules/todos/useTodos'

type Filter = 'all' | 'active' | 'completed'

const { allTodos, activeTodos, completedTodos, addTodo, toggleTodo, deleteTodo } = useTodos()

const filter = ref<Filter>('all')
const input = ref('')

const filteredTodos = computed(() => {
	if (filter.value === 'active') return activeTodos.value
	if (filter.value === 'completed') return completedTodos.value
	return allTodos.value
})

function handleSubmit(): void {
	const title = input.value.trim()
	if (!title) return
	addTodo.mutate({ title })
	input.value = ''
}

function clearCompleted(): void {
	for (const todo of completedTodos.value) {
		deleteTodo.mutate(todo.id)
	}
}

function emptyMessage(f: Filter): string {
	if (f === 'all') return 'No tasks yet. Add one above!'
	if (f === 'active') return 'All caught up! No active tasks.'
	return 'No completed tasks yet.'
}
</script>

<template>
	<div class="min-h-screen bg-gray-950 text-gray-100">
		<div class="mx-auto max-w-2xl px-4 py-12">
			<div class="mb-8 flex items-center gap-3">
				<ClipboardList class="h-8 w-8 text-indigo-400" />
				<h1 class="text-2xl font-bold">My Tasks</h1>
			</div>

			<div class="mb-8 grid grid-cols-3 gap-4">
				<div class="rounded-lg border border-gray-800 bg-gray-900 p-4">
					<p class="text-sm text-gray-500">Total</p>
					<p class="text-2xl font-bold text-gray-300">{{ allTodos.length }}</p>
				</div>
				<div class="rounded-lg border border-gray-800 bg-gray-900 p-4">
					<p class="text-sm text-gray-500">Remaining</p>
					<p class="text-2xl font-bold text-amber-400">{{ activeTodos.length }}</p>
				</div>
				<div class="rounded-lg border border-gray-800 bg-gray-900 p-4">
					<p class="text-sm text-gray-500">Done</p>
					<p class="text-2xl font-bold text-emerald-400">{{ completedTodos.length }}</p>
				</div>
			</div>

			<form class="mb-8 flex gap-3" @submit.prevent="handleSubmit">
				<input
					v-model="input"
					type="text"
					placeholder="What needs to be done?"
					class="flex-1 rounded-lg border border-gray-700 bg-gray-900 px-4 py-3 text-gray-100 placeholder-gray-500 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
				/>
				<button
					type="submit"
					:disabled="addTodo.isLoading.value || !input.trim()"
					class="flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 font-medium text-white transition hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-50"
				>
					<Loader2 v-if="addTodo.isLoading.value" class="h-4 w-4 animate-spin" />
					<Plus v-else class="h-4 w-4" />
					Add
				</button>
			</form>

			<div class="mb-6 flex gap-2">
				<button
					v-for="f in (['all', 'active', 'completed'] as const)"
					:key="f"
					type="button"
					:class="[
						'flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition',
						filter === f
							? 'bg-indigo-600 text-white'
							: 'bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-gray-200',
					]"
					@click="filter = f"
				>
					{{ f.charAt(0).toUpperCase() + f.slice(1) }}
				</button>
			</div>

			<div class="space-y-2">
				<div
					v-if="filteredTodos.length === 0"
					class="rounded-lg border border-dashed border-gray-800 py-12 text-center text-gray-600"
				>
					{{ emptyMessage(filter) }}
				</div>
				<template v-else>
					<div
						v-for="todo in filteredTodos"
						:key="todo.id"
						class="group flex items-center gap-3 rounded-lg border border-gray-800 bg-gray-900 px-4 py-3"
					>
						<button
							type="button"
							class="shrink-0 text-gray-500 hover:text-indigo-400"
							@click="toggleTodo.mutate(todo.id, { completed: !todo.completed })"
						>
							<CheckCircle2 v-if="todo.completed" class="h-5 w-5 text-emerald-400" />
							<Circle v-else class="h-5 w-5" />
						</button>
						<span :class="['flex-1', todo.completed ? 'line-through text-gray-500' : '']">
							{{ String(todo.title) }}
						</span>
						<button
							type="button"
							class="text-gray-600 opacity-0 group-hover:opacity-100 hover:text-red-400"
							@click="deleteTodo.mutate(todo.id)"
						>
							<Trash2 class="h-4 w-4" />
						</button>
					</div>
				</template>
			</div>

			<p class="mt-12 text-center text-xs text-gray-700">Powered by Kora — offline-first</p>
		</div>
	</div>
</template>

// packages/cli/templates/react-tailwind/src/App.tsx
import { CheckCircle2, Circle, ClipboardList, Loader2, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { useTodos } from './modules/todos/useTodos'

type Filter = 'all' | 'active' | 'completed'

export function App() {
	const { allTodos, activeTodos, completedTodos, addTodo, toggleTodo, deleteTodo } = useTodos()
	const isAdding = addTodo.isLoading

	const [filter, setFilter] = useState<Filter>('all')
	const [input, setInput] = useState('')

	const filteredTodos =
		filter === 'active' ? activeTodos : filter === 'completed' ? completedTodos : allTodos

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault()
		const title = input.trim()
		if (title) {
			addTodo.mutate({ title })
			setInput('')
		}
	}

	const clearCompleted = () => {
		for (const todo of completedTodos) {
			deleteTodo.mutate(todo.id)
		}
	}

	return (
		<div className="min-h-screen bg-gray-950 text-gray-100">
			<div className="mx-auto max-w-2xl px-4 py-12">
				{/* Header */}
				<div className="flex items-center justify-between mb-8">
					<div className="flex items-center gap-3">
						<ClipboardList className="h-8 w-8 text-indigo-400" />
						<h1 className="text-2xl font-bold">My Tasks</h1>
					</div>
					<span className="rounded-full bg-gray-800 px-3 py-1.5 text-sm text-gray-400">
						Local-first
					</span>
				</div>

				{/* Stats */}
				<div className="grid grid-cols-3 gap-4 mb-8">
					<StatCard label="Total" value={allTodos.length} color="text-gray-300" />
					<StatCard label="Remaining" value={activeTodos.length} color="text-amber-400" />
					<StatCard label="Done" value={completedTodos.length} color="text-emerald-400" />
				</div>

				{/* Add form */}
				<form onSubmit={handleSubmit} className="flex gap-3 mb-8">
					<input
						type="text"
						value={input}
						onChange={(e) => setInput(e.target.value)}
						placeholder="What needs to be done?"
						className="flex-1 rounded-lg border border-gray-700 bg-gray-900 px-4 py-3 text-gray-100 placeholder-gray-500 outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
					/>
					<button
						type="submit"
						disabled={isAdding || !input.trim()}
						className="flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 font-medium text-white transition hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
					>
						{isAdding ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}
						Add
					</button>
				</form>

				{/* Filter tabs */}
				<div className="flex gap-2 mb-6">
					{(['all', 'active', 'completed'] as const).map((f) => {
						const count =
							f === 'all'
								? allTodos.length
								: f === 'active'
									? activeTodos.length
									: completedTodos.length
						return (
							<button
								key={f}
								onClick={() => setFilter(f)}
								className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition ${
									filter === f
										? 'bg-indigo-600 text-white'
										: 'bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-gray-200'
								}`}
							>
								{f.charAt(0).toUpperCase() + f.slice(1)}
								<span
									className={`rounded-full px-2 py-0.5 text-xs ${
										filter === f ? 'bg-indigo-500 text-white' : 'bg-gray-700 text-gray-400'
									}`}
								>
									{count}
								</span>
							</button>
						)
					})}
				</div>

				{/* Todo list */}
				<div className="space-y-2">
					{filteredTodos.length === 0 ? (
						<EmptyState filter={filter} />
					) : (
						filteredTodos.map((todo) => (
							<div
								key={todo.id}
								className="group flex items-center gap-3 rounded-lg border border-gray-800 bg-gray-900 px-4 py-3 transition hover:border-gray-700"
							>
								<button
									onClick={() => toggleTodo.mutate(todo.id, { completed: !todo.completed })}
									className="shrink-0 text-gray-500 hover:text-indigo-400 transition"
								>
									{todo.completed ? (
										<CheckCircle2 className="h-5 w-5 text-emerald-400" />
									) : (
										<Circle className="h-5 w-5" />
									)}
								</button>
								<span
									className={`flex-1 ${
										todo.completed ? 'text-gray-500 line-through' : 'text-gray-100'
									}`}
								>
									{String(todo.title)}
								</span>
								{todo.createdAt && (
									<span className="text-xs text-gray-600">
										{formatTime(Number(todo.createdAt))}
									</span>
								)}
								<button
									onClick={() => deleteTodo.mutate(todo.id)}
									className="shrink-0 text-gray-600 opacity-0 transition hover:text-red-400 group-hover:opacity-100"
								>
									<Trash2 className="h-4 w-4" />
								</button>
							</div>
						))
					)}
				</div>

				{/* Footer */}
				{allTodos.length > 0 && (
					<div className="mt-6 flex items-center justify-between text-sm text-gray-500">
						<span>
							{activeTodos.length} item{activeTodos.length !== 1 ? 's' : ''} left
						</span>
						{completedTodos.length > 0 && (
							<button
								onClick={clearCompleted}
								className="text-gray-500 transition hover:text-gray-300"
							>
								Clear completed
							</button>
						)}
					</div>
				)}

				<p className="mt-12 text-center text-xs text-gray-700">
					Powered by Kora &mdash; offline-first, real-time sync
				</p>
			</div>
		</div>
	)
}

function StatCard({ label, value, color }: { label: string; value: number; color: string }) {
	return (
		<div className="rounded-lg border border-gray-800 bg-gray-900 p-4">
			<p className="text-sm text-gray-500">{label}</p>
			<p className={`text-2xl font-bold ${color}`}>{value}</p>
		</div>
	)
}

function EmptyState({ filter }: { filter: Filter }) {
	const messages: Record<Filter, string> = {
		all: 'No tasks yet. Add one above!',
		active: 'All caught up! No active tasks.',
		completed: 'No completed tasks yet.',
	}
	return (
		<div className="rounded-lg border border-dashed border-gray-800 py-12 text-center text-gray-600">
			{messages[filter]}
		</div>
	)
}

function formatTime(timestamp: number): string {
	const date = new Date(timestamp)
	const now = new Date()
	if (date.toDateString() === now.toDateString()) {
		return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
	}
	return date.toLocaleDateString([], { month: 'short', day: 'numeric' })
}
